default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: compedia_development

test:
  <<: *default
  database: compedia_test

production:
  primary: &primary_production
    <<: *default
    database: compedia_production
    username: compedia
    password: <%= ENV["COMPEDIA_DATABASE_PASSWORD"] %>
  cache:
    <<: *primary_production
    database: compedia_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: compedia_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: compedia_production_cable
    migrations_paths: db/cable_migrate
